name: GoldBigDragonRPG
main: GoldBigDragon_RPG.Main.Main
version: 20160816
description: Mabinogi!!!
commands:
  돈:
    description: 자신의 소지 금액을 확인합니다.
  스텟:
    description: 캐릭터의 스텟을 확인합니다.
  옵션:
    description: 게임 옵션을 조절합니다.
  기타:
    description: 기타 기능들을 확인합니다.
  파티:
    description: 파티 관련 GUI창을 엽니다.
  오피박스:
    description: 서버 OP만의 설정 GUI창을 엽니다.
  아이템:
    description: 아이템 관련 명령어를 실행합니다.
  몬스터:
    description: 몬스터 관련 명령어를 실행합니다.
  워프:
    description: 워프 관련 명령어를 실행합니다.
  영역:
    description: 영역 관련 명령어를 실행합니다.
  상점:
    description: NPC의 상점 관련 명령어를 실행합니다.
  엔티티제거:
    description: 플레이어, 아이템 액자, 아머 스탠드를 제외한 모든 엔티티를 제거합니다.
  아이템제거:
    description: 반경 내에 떨어진 모든 아이템을 제거합니다.
  강제철거:
    description: 모든 엔티티를 강제로 철거해 버립니다.
  퀘스트:
    description: 퀘스트 관련 GUI창을 엽니다.
  커맨드:
    description: 스킬 커맨드 등록용 커맨드 입니다.
  스킬:
    description: 자신의 스킬 창을 확인합니다.
  친구:
    description: 친구 GUI창을 엽니다.
  gui사용:
    description: 비활성화 시킨 NPC의 GUI창을 활성화 시킵니다.
  테스트:
    description: 테스트용 명령어 입니다.
  테스트2:
    description: 테스트용 명령어 입니다.
  수락:
    description: 상대방 요청을 수락니다.
  거절:
    description: 상대방 요청을 거절합니다.
  타입추가:
    description: 무기 타입을 추가합니다.
  스텟초기화권:
    description: 스텟 초기화 주문서를 얻습니다. /스텟초기화권 [이름] 을 통해 다른사람에게도 줄 수 있습니다.