world: world
lobby_x: 386
lobby_y: 43
lobby_z: 245
loc_x: -13
loc_y: 64
loc_z: -28
bl_0_x: -10
bl_0_y: 64
bl_0_z: -29
bl_1_x: -10
bl_1_y: 64
bl_1_z: -28
bl_2_x: -10
bl_2_y: 64
bl_2_z: -27
bl_3_x: -10
bl_3_y: 65
bl_3_z: -29
bl_4_x: -10
bl_4_y: 65
bl_4_z: -28
bl_5_x: -10
bl_5_y: 65
bl_5_z: -27
bl_6_x: -10
bl_6_y: 66
bl_6_z: -29
bl_7_x: -10
bl_7_y: 66
bl_7_z: -28
bl_8_x: -10
bl_8_y: 66
bl_8_z: -27
top: 0
top_name: Bokum